import type { QuizQuestion } from "@/features/diagnosis/types/quiz";

export const QUESTIONS: QuizQuestion[] = [
  {
    key: "birthYear",
    highlight: "生まれ年",
    category: 0,
    options: [
      { label: "1990年以前", emoji: "🏔️" },
      { label: "1991〜1995年", emoji: "🌳" },
      { label: "1996〜2000年", emoji: "🌿" },
      { label: "2001年以降", emoji: "🌱" },
    ],
  },
  {
    key: "education",
    highlight: "最終学歴",
    category: 0,
    options: [
      { label: "高校", emoji: "🏫" },
      { label: "専門学校", emoji: "🔧" },
      { label: "短大", emoji: "📚" },
      { label: "大学", emoji: "🎓" },
      { label: "大学院", emoji: "🔬" },
    ],
  },
  {
    key: "schoolTier",
    highlight: "出身校の水準",
    subtitle: "大学・大学院の水準を選んでください",
    category: 0,
    showIf: (a) => a.education === "大学" || a.education === "大学院",
    options: [
      { label: "旧帝大・早慶", emoji: "🏆" },
      { label: "MARCH・関関同立", emoji: "⭐" },
      { label: "日東駒専・産近甲龍", emoji: "📖" },
      { label: "その他の大学", emoji: "🎓" },
    ],
  },
  {
    key: "graduationYear",
    highlight: "卒業年",
    category: 0,
    options: [
      { label: "2024年以降", emoji: "🌱" },
      { label: "2020〜2023年", emoji: "🌿" },
      { label: "2016〜2019年", emoji: "🌳" },
      { label: "2011〜2015年", emoji: "🏔️" },
      { label: "2010年以前", emoji: "🗻" },
    ],
  },
  {
    key: "companyType",
    highlight: "勤務先のタイプ",
    category: 1,
    options: [
      { label: "外資系大手", emoji: "🌐" },
      { label: "国内大手上場企業", emoji: "🏢" },
      { label: "中堅・ベンチャー上場", emoji: "📈" },
      { label: "非上場ベンチャー", emoji: "🚀" },
      { label: "中小企業・その他", emoji: "🏪" },
    ],
  },
  {
    key: "employmentType",
    highlight: "雇用形態",
    category: 1,
    options: [
      { label: "正社員", emoji: "💼" },
      { label: "契約社員", emoji: "📋" },
      { label: "派遣社員", emoji: "🔄" },
      { label: "フリーランス", emoji: "⚡" },
      { label: "その他", emoji: "✨" },
    ],
  },
  {
    key: "industryLevel1",
    highlight: "関わっている業界",
    category: 1,
    options: [
      { label: "IT/インターネット/通信", emoji: "💻" },
      { label: "金融/保険", emoji: "💰" },
      { label: "コンサルティング", emoji: "📊" },
      { label: "メーカー/製造業", emoji: "🏭" },
      { label: "商社/卸売", emoji: "🚢" },
      { label: "その他", emoji: "✨" },
    ],
  },
  {
    key: "industryLevel3",
    highlight: "より具体的な領域",
    category: 1,
    showIf: (a) => a.industryLevel1 === "IT/インターネット/通信",
    options: [
      { label: "SaaS/クラウドサービス", emoji: "☁️" },
      { label: "フィンテック/ブロックチェーン", emoji: "💎" },
      { label: "AI/機械学習", emoji: "🤖" },
      { label: "ECプラットフォーム", emoji: "🛒" },
      { label: "ゲーム/エンタメ", emoji: "🎮" },
      { label: "その他IT", emoji: "💻" },
    ],
  },
  {
    key: "companySize",
    highlight: "従業員数",
    category: 1,
    options: [
      { label: "10人未満", emoji: "👤" },
      { label: "10〜49人", emoji: "👥" },
      { label: "50〜299人", emoji: "🏢" },
      { label: "300〜999人", emoji: "🏙️" },
      { label: "1000〜2999人", emoji: "🌆" },
      { label: "3000人以上", emoji: "🌇" },
    ],
  },
  {
    key: "position",
    highlight: "現在の役職",
    category: 1,
    options: [
      { label: "代表/役員", emoji: "👑" },
      { label: "部長/マネージャー", emoji: "🎯" },
      { label: "課長/チームリーダー", emoji: "📌" },
      { label: "主任/リーダー", emoji: "⭐" },
      { label: "役職なし", emoji: "💼" },
    ],
  },
  {
    key: "currentIncome",
    highlight: "現在の年収",
    category: 1,
    options: [
      { label: "〜300万", emoji: "💴" },
      { label: "300〜400万", emoji: "💰" },
      { label: "400〜500万", emoji: "💎" },
      { label: "500〜600万", emoji: "👑" },
      { label: "600〜800万", emoji: "🏆" },
      { label: "800万〜", emoji: "🚀" },
    ],
  },
  {
    key: "jobLevel1",
    highlight: "主な経験職種",
    category: 2,
    options: [
      { label: "営業", emoji: "💬" },
      { label: "マーケティング/企画", emoji: "📊" },
      { label: "ITエンジニア", emoji: "💻" },
      { label: "コンサルタント", emoji: "🎯" },
      { label: "管理部門", emoji: "📋" },
      { label: "その他", emoji: "✨" },
    ],
  },
  {
    key: "jobLevel3",
    highlight: "より具体的な職種",
    category: 2,
    showIf: (a) => !!a.jobLevel1,
    options: (answers) => {
      if (answers.jobLevel1 === "営業") {
        return [
          { label: "法人営業（大手向け）", emoji: "🏢" },
          { label: "法人営業（中小向け）", emoji: "🏪" },
          { label: "個人営業", emoji: "👤" },
          { label: "代理店営業", emoji: "🤝" },
          { label: "インサイドセールス", emoji: "📱" },
          { label: "その他営業", emoji: "✨" },
        ];
      }
      if (answers.jobLevel1 === "ITエンジニア") {
        return [
          { label: "バックエンドエンジニア", emoji: "⚙️" },
          { label: "フロントエンドエンジニア", emoji: "🖥️" },
          { label: "インフラ/SRE", emoji: "☁️" },
          { label: "機械学習/AI", emoji: "🤖" },
          { label: "その他エンジニア", emoji: "💻" },
        ];
      }
      return [
        { label: "企画/戦略", emoji: "📊" },
        { label: "マーケティング", emoji: "📣" },
        { label: "経営管理/財務", emoji: "💰" },
        { label: "コンサルティング", emoji: "🎯" },
        { label: "その他", emoji: "✨" },
      ];
    },
  },
  {
    key: "yearsOfExperience",
    highlight: "職種の経験年数",
    category: 2,
    options: [
      { label: "1年未満", emoji: "🌱" },
      { label: "1〜2年", emoji: "🌿" },
      { label: "2〜4年", emoji: "🌳" },
      { label: "4年以上", emoji: "🏔️" },
    ],
  },
  {
    key: "customerSize",
    highlight: "担当顧客の規模",
    category: 3,
    showIf: (a) => a.jobLevel1 === "営業",
    options: [
      { label: "個人・小規模（〜50名）", emoji: "👤" },
      { label: "中小企業（51〜300名）", emoji: "🏪" },
      { label: "中堅企業（301〜1000名）", emoji: "🏢" },
      { label: "大企業（1001〜5000名）", emoji: "🌆" },
      { label: "エンタープライズ（5000名〜）", emoji: "🌇" },
    ],
  },
  {
    key: "achievementRate",
    highlight: "営業目標の達成率",
    category: 3,
    showIf: (a) => a.jobLevel1 === "営業",
    options: [
      { label: "60%未満", emoji: "😓" },
      { label: "60〜80%", emoji: "😐" },
      { label: "80〜100%", emoji: "🙂" },
      { label: "100〜120%", emoji: "😊" },
      { label: "120%以上", emoji: "🔥" },
    ],
  },
  {
    key: "rankInOrg",
    highlight: "組織内の営業成績",
    category: 3,
    showIf: (a) => a.jobLevel1 === "営業",
    options: [
      { label: "下位（60%以下）", emoji: "😓" },
      { label: "中位（40〜60%）", emoji: "😐" },
      { label: "上位（20〜40%）", emoji: "😊" },
      { label: "上位（10〜20%）", emoji: "⭐" },
      { label: "トップ（10%以内）", emoji: "🏆" },
    ],
  },
  {
    key: "salesProduct",
    highlight: "取り扱い商材",
    category: 3,
    showIf: (a) => a.jobLevel1 === "営業",
    options: [
      { label: "クラウド/SaaS", emoji: "☁️" },
      { label: "人材/採用サービス", emoji: "👥" },
      { label: "広告/マーケティング", emoji: "📣" },
      { label: "物流/インフラ", emoji: "🚢" },
      { label: "その他", emoji: "✨" },
    ],
  },
  {
    key: "productPrice",
    highlight: "取引商材の単価",
    category: 3,
    showIf: (a) => a.jobLevel1 === "営業",
    options: [
      { label: "10万円未満", emoji: "💴" },
      { label: "10〜100万", emoji: "💰" },
      { label: "100万〜1000万", emoji: "💎" },
      { label: "1000万〜1億", emoji: "🏆" },
      { label: "1億以上", emoji: "🚀" },
    ],
  },
  {
    key: "managementYears",
    highlight: "マネジメント経験",
    category: 4,
    options: [
      { label: "なし", emoji: "❌" },
      { label: "1年未満", emoji: "🌱" },
      { label: "1〜2年", emoji: "🌿" },
      { label: "2年以上", emoji: "🌳" },
    ],
  },
  {
    key: "englishLevel",
    highlight: "英語力",
    category: 4,
    options: [
      { label: "なし/初級", emoji: "🔤" },
      { label: "日常会話レベル", emoji: "💬" },
      { label: "ビジネス会話レベル", emoji: "🎯" },
      { label: "ネイティブ/流暢", emoji: "🌐" },
    ],
  },
];
