import type { TierDef } from './diagnosis.types';

export const OCCUPATION_TYPES: Array<{ code: string; label: string }> = [
  { code: 'apparel_cosmetics', label: 'アパレル・コスメ' },
  { code: 'security_guard', label: '警備員' },
  { code: 'factory_manufacturing', label: '工場・製造業' },
  { code: 'tutor', label: '塾講師' },
  { code: 'call_center', label: 'コールセンター' },
  { code: 'resort_jobs', label: 'リゾートバイト' },
  { code: 'girls_bar_concept_cafe', label: 'ガールズバー・コンカフェ' },
  { code: 'caregiving', label: '介護' },
  { code: 'chat_hostess', label: 'チャットレディー' },
  { code: 'food_beverage', label: '飲食' },
  { code: 'taxi_driver', label: 'タクシードライバー' },
  { code: 'truck_driver', label: 'トラックドライバー' },
  { code: 'remote_work', label: '在宅ワーク' },
  { code: 'marketing_creative', label: 'マーケティング・クリエイティブ' },
  { code: 'housekeeping', label: '家事代行' },
  { code: 'consulting', label: 'コンサル' },
  { code: 'construction', label: '建設' },
  { code: 'real_estate', label: '不動産' },
  { code: 'sales_reception', label: '販売・受付' },
  { code: 'supermarket_fresh_food', label: 'スーパー・生鮮' },
  { code: 'translation', label: '翻訳' },
  { code: 'back_office_administration', label: 'バックオフィス・事務' },
  { code: 'venture_startup', label: 'ベンチャー・スタートアップ' },
  { code: 'it_engineer', label: 'ITエンジニア' },
  { code: 'ma', label: 'M&A' },
  { code: 'foreign_affiliated', label: '外資系' },
  { code: 'sales', label: '営業' },
  { code: 'human_resources', label: '人材' },
  { code: 'doctor', label: '医師' },
  { code: 'nurse', label: '看護師' },
  { code: 'pharmacist', label: '薬剤師' },
  { code: 'physical_therapist', label: '理学療法士' },
  { code: 'dentist', label: '歯科医師' },
  { code: 'dental_hygienist', label: '歯科衛生士' },
  { code: 'hair_stylist', label: '美容師' },
  { code: 'seitai_therapist', label: '整体師' },
  { code: 'certified_tax_accountant', label: '税理士' },
  { code: 'certified_public_accountant', label: '公認会計士' },
  { code: 'nail_technician', label: 'ネイリスト' },
  { code: 'eyelash_technician', label: 'アイリスト' },
  { code: 'eyebrow_technician', label: 'アイブロウリスト' },
  { code: 'esthetician', label: 'エステティシャン' },
  { code: 'therapist', label: 'セラピスト' },
];

export const INCOME_BASE: Record<string, number> = {
  '〜300万': 270,
  '300〜400万': 350,
  '400〜500万': 450,
  '500〜600万': 520,
  '600〜800万': 680,
  '800万〜': 850,
};

export const SCORE_MAP: Record<string, Record<string, number>> = {
  birthYear: {
    '1990年以前': 10,
    '1991〜1995年': 12,
    '1996〜2000年': 10,
    '2001年以降': 5,
  },
  education: {
    '高校': 0,
    '専門学校': 3,
    '短大': 3,
    '大学': 8,
    '大学院': 12,
  },
  schoolTier: {
    '旧帝大・早慶': 15,
    'MARCH・関関同立': 10,
    '日東駒専・産近甲龍': 6,
    'その他の大学': 3,
  },
  graduationYear: {
    '2024年以降': 2,
    '2020〜2023年': 5,
    '2016〜2019年': 10,
    '2011〜2015年': 12,
    '2010年以前': 14,
  },
  companyType: {
    '外資系大手': 20,
    '国内大手上場企業': 15,
    '中堅・ベンチャー上場': 10,
    '非上場ベンチャー': 8,
    '中小企業・その他': 4,
  },
  employmentType: {
    '正社員': 12,
    '契約社員': 5,
    '派遣社員': 3,
    'フリーランス': 10,
    'その他': 2,
  },
  industryLevel1: {
    'IT/インターネット/通信': 15,
    '金融/保険': 12,
    'コンサルティング': 12,
    'メーカー/製造業': 8,
    '商社/卸売': 8,
    'その他': 4,
  },
  industryLevel3: {
    'SaaS/クラウドサービス': 15,
    'フィンテック/ブロックチェーン': 12,
    'AI/機械学習': 12,
    'ECプラットフォーム': 8,
    'ゲーム/エンタメ': 6,
    'その他IT': 5,
  },
  companySize: {
    '10人未満': 3,
    '10〜49人': 5,
    '50〜299人': 7,
    '300〜999人': 10,
    '1000〜2999人': 12,
    '3000人以上': 14,
  },
  position: {
    '代表/役員': 20,
    '部長/マネージャー': 15,
    '課長/チームリーダー': 10,
    '主任/リーダー': 7,
    '役職なし': 3,
  },
  currentIncome: {
    '〜300万': 0,
    '300〜400万': 5,
    '400〜500万': 10,
    '500〜600万': 15,
    '600〜800万': 18,
    '800万〜': 20,
  },
  jobLevel1: {
    '営業': 12,
    'マーケティング/企画': 10,
    'ITエンジニア': 15,
    'コンサルタント': 15,
    '管理部門': 8,
    'その他': 5,
  },
  jobLevel3: {
    '法人営業（大手向け）': 15,
    '法人営業（中小向け）': 10,
    '個人営業': 6,
    '代理店営業': 8,
    'インサイドセールス': 8,
    'その他営業': 4,
    'バックエンドエンジニア': 12,
    'フロントエンドエンジニア': 10,
    'インフラ/SRE': 14,
    '機械学習/AI': 15,
    'その他エンジニア': 8,
    '企画/戦略': 12,
    'マーケティング': 10,
    '経営管理/財務': 10,
    'コンサルティング': 14,
    'その他': 5,
  },
  yearsOfExperience: {
    '1年未満': 0,
    '1〜2年': 3,
    '2〜4年': 6,
    '4年以上': 10,
  },
  customerSize: {
    '個人・小規模（〜50名）': 3,
    '中小企業（51〜300名）': 6,
    '中堅企業（301〜1000名）': 10,
    '大企業（1001〜5000名）': 13,
    'エンタープライズ（5000名〜）': 16,
  },
  achievementRate: {
    '60%未満': 0,
    '60〜80%': 5,
    '80〜100%': 10,
    '100〜120%': 15,
    '120%以上': 20,
  },
  rankInOrg: {
    '下位（60%以下）': 0,
    '中位（40〜60%）': 5,
    '上位（20〜40%）': 10,
    '上位（10〜20%）': 14,
    'トップ（10%以内）': 18,
  },
  salesProduct: {
    'クラウド/SaaS': 15,
    '人材/採用サービス': 10,
    '広告/マーケティング': 8,
    '物流/インフラ': 6,
    'その他': 4,
  },
  productPrice: {
    '10万円未満': 0,
    '10〜100万': 5,
    '100万〜1000万': 12,
    '1000万〜1億': 18,
    '1億以上': 24,
  },
  managementYears: {
    'なし': 0,
    '1年未満': 3,
    '1〜2年': 6,
    '2年以上': 12,
  },
  englishLevel: {
    'なし/初級': 0,
    '日常会話レベル': 5,
    'ビジネス会話レベル': 10,
    'ネイティブ/流暢': 15,
  },
};

export const MAX_SCORES: Record<string, number> = {
  birthYear: 12,
  education: 12,
  schoolTier: 15,
  graduationYear: 14,
  companyType: 20,
  employmentType: 12,
  industryLevel1: 15,
  industryLevel3: 15,
  companySize: 14,
  position: 20,
  currentIncome: 20,
  jobLevel1: 15,
  jobLevel3: 15,
  yearsOfExperience: 10,
  customerSize: 16,
  achievementRate: 20,
  rankInOrg: 18,
  salesProduct: 15,
  productPrice: 24,
  managementYears: 12,
  englishLevel: 15,
};

export const TIERS: TierDef[] = [
  {
    id: 'high_potential',
    name: 'ハイポテンシャル層',
    emoji: '🚀',
    rank: 'S',
    growthType: '市場トップクラス型',
    tagline: 'あなたの経験は、市場の上位数%が持つ希少価値です',
    description:
      'IT/SaaS・大手企業・エンタープライズ営業・高単価商材などの組み合わせが市場価値を大きく高めています。今の年収は実力の7〜8割しか反映されていない可能性があります。',
  },
  {
    id: 'mid_senior',
    name: '即戦力ミドル層',
    emoji: '💼',
    rank: 'A',
    growthType: '30代ジャンプ型',
    tagline: '今の経験を正しく評価してくれる会社に移るだけで、年収は変わります',
    description:
      '現職での実績・業界知識・商材経験が市場で評価される水準に達しています。職場環境や評価制度を変えることで、年収が一段階上がる可能性が高いです。',
  },
  {
    id: 'standard',
    name: '標準的キャリア層',
    emoji: '📈',
    rank: 'B',
    growthType: '着実成長型',
    tagline: 'スキルの掛け合わせ次第で、次の水準へ上がれます',
    description:
      '現年収と近い水準で安定していますが、特定のスキルや業界知識を深めることで上振れ余地があります。転職よりもスキルアップが先の可能性もあります。',
  },
  {
    id: 'growth',
    name: '成長余地あり層',
    emoji: '🌱',
    rank: 'B',
    growthType: '経験積み上げ型',
    tagline: '今は仕込み時期。3年後のあなたは全然違います',
    description:
      '経験年数や成果指標はまだ途中段階ですが、伸びしろが大きい時期です。スキル習得・業界変更・成果実績の積み上げで、年収が大きく変わってきます。',
  },
  {
    id: 'redesign',
    name: 'キャリア再設計層',
    emoji: '🔄',
    rank: 'B',
    growthType: '方向転換型',
    tagline: '今の方向性を少し変えるだけで、大きく変わる可能性があります',
    description:
      '職種・業界・雇用形態の組み合わせを見直すことで、収入アップのルートが開けます。現状の延長線よりも、一度立ち止まってキャリアを整理することが先決です。',
  },
];
